"""Add Lecture model

Revision ID: dead57d0ac06
Revises: eaae517c1e2f
Create Date: 2023-05-10 07:12:15.970857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dead57d0ac06'
down_revision = 'eaae517c1e2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lecture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lecture_id'), 'lecture', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lecture_id'), table_name='lecture')
    op.drop_table('lecture')
    # ### end Alembic commands ###
